
    create table Asociaciones (
        id_asociacion bigint generated by default as identity (start with 1),
        direccion varchar(255),
        latitud double,
        longitud double,
        primary key (id_asociacion)
    )

    create table Atributos (
        id_atributo bigint generated by default as identity (start with 1),
        valor_atributo varchar(255),
        caracteristica_id bigint,
        mascota_id bigint,
        primary key (id_atributo)
    )

    create table Caracteristicas (
        tipo_caracteristica varchar(31) not null,
        id_caracteristica bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (id_caracteristica)
    )

    create table Contactos (
        tipo_contacto varchar(31) not null,
        id_contacto bigint generated by default as identity (start with 1),
        nombre_apellido varchar(255),
        telefono varchar(255),
        email varchar(255),
        persona_id bigint,
        primary key (id_contacto)
    )

    create table Duenios_mascota (
        id_duenio bigint generated by default as identity (start with 1),
        persona_id bigint,
        usuario_id bigint,
        primary key (id_duenio)
    )

    create table IntencionesAdoptar (
        id_intencion_adoptar bigint generated by default as identity (start with 1),
        estadoAdopcion varchar(255),
        tipo_mascota varchar(255),
        persona_id bigint,
        id_asociacion bigint,
        primary key (id_intencion_adoptar)
    )

    create table Mascotas (
        id_mascota bigint generated by default as identity (start with 1),
        apodo varchar(255),
        descripcionFisica varchar(255),
        fecha_nacimiento date,
        nombre varchar(255),
        sexo varchar(255),
        tamanio varchar(255),
        tipo varchar(255),
        duenio_id bigint,
        primary key (id_mascota)
    )

    create table Mascotas_Encontradas (
        id_mascota_encontrada bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        estado varchar(255),
        fecha_rescate date,
        direccion varchar(255),
        latitud double,
        longitud double,
        tamanio varchar(255),
        tipo varchar(255),
        mascota_id bigint,
        persona_id bigint,
        id_asociacion bigint,
        primary key (id_mascota_encontrada)
    )

    create table Mascotas_en_adopcion (
        id_mascota_adopcion bigint generated by default as identity (start with 1),
        mascota_id bigint,
        id_asociacion bigint,
        primary key (id_mascota_adopcion)
    )

    create table Personas (
        id_persona bigint generated by default as identity (start with 1),
        direccion varchar(255),
        latitud double,
        longitud double,
        fecha_nacimiento date,
        nombre_apellido varchar(255),
        nroDocumento varchar(255),
        tipo_documento varchar(255),
        primary key (id_persona)
    )

    create table Preguntas_Adopcion (
        id_preguntas_adopcion bigint generated by default as identity (start with 1),
        identificador varchar(255),
        pregunta_adoptante varchar(255),
        pregunta_duenio varchar(255),
        id_asociacion bigint,
        primary key (id_preguntas_adopcion)
    )

    create table Publicaciones (
        id_publicacion bigint generated by default as identity (start with 1),
        estado_publicacion varchar(255),
        mascota_encontrada_id bigint,
        id_asociacion bigint,
        primary key (id_publicacion)
    )

    create table Respuestas_Posibles (
        pregunta_adopcion_id bigint not null,
        respuesta varchar(255)
    )

    create table Respuestas_Pregunta_Adopcion (
        id_respuesta bigint generated by default as identity (start with 1),
        valor_respuesta varchar(255),
        pregunta_adopcion_id bigint,
        intencion_adoptar_id bigint,
        mascota_adopcion_id bigint,
        primary key (id_respuesta)
    )

    create table Usuario (
        id_usuario bigint generated by default as identity (start with 1),
        password varchar(255),
        rol varchar(255),
        username varchar(255),
        primary key (id_usuario)
    )

    create table Valores_Caracteristicas (
        caracteristica_id bigint not null,
        valor varchar(255)
    )

    create table fotos_mascotas (
        mascota_id bigint not null,
        pathFotos varchar(255)
    )

    create table fotos_mascotas_encontradas (
        mascota_encontrada_id bigint not null,
        pathFotos varchar(255)
    )

    alter table Atributos 
        add constraint FK_4pqagb3apuam762ixson0rvqf 
        foreign key (caracteristica_id) 
        references Caracteristicas

    alter table Atributos 
        add constraint FK_o5r9bkw155329oyfd53wmidr4 
        foreign key (mascota_id) 
        references Mascotas

    alter table Contactos 
        add constraint FK_3cbt0hm8i82kwse200vm9lh49 
        foreign key (persona_id) 
        references Personas

    alter table Duenios_mascota 
        add constraint FK_5rp3nxv3k7roaaldpbptx4b6u 
        foreign key (persona_id) 
        references Personas

    alter table Duenios_mascota 
        add constraint FK_t5rk2mw4gnq1tn2qxij1v0a11 
        foreign key (usuario_id) 
        references Usuario

    alter table IntencionesAdoptar 
        add constraint FK_i60iygcm01jol4mtvnf4ksaq0 
        foreign key (persona_id) 
        references Personas

    alter table IntencionesAdoptar 
        add constraint FK_mcuv3ibsqjayndih6xv6mfg9b 
        foreign key (id_asociacion) 
        references Asociaciones

    alter table Mascotas 
        add constraint FK_nvg31pbtdkdobq5ip1iy04tu9 
        foreign key (duenio_id) 
        references Duenios_mascota

    alter table Mascotas_Encontradas 
        add constraint FK_bc9k6f1mwhr75kj5n6hy164bo 
        foreign key (mascota_id) 
        references Mascotas

    alter table Mascotas_Encontradas 
        add constraint FK_b5emw8vc7pk2buj3yr9i21hf5 
        foreign key (persona_id) 
        references Personas

    alter table Mascotas_Encontradas 
        add constraint FK_m0g6y0fqec5amq1jhyr2xjech 
        foreign key (id_asociacion) 
        references Asociaciones

    alter table Mascotas_en_adopcion 
        add constraint FK_qnlp4mhm7a1eyjcbapfonyw01 
        foreign key (mascota_id) 
        references Mascotas

    alter table Mascotas_en_adopcion 
        add constraint FK_irq1prcesfqtgq4phbbh88nxi 
        foreign key (id_asociacion) 
        references Asociaciones

    alter table Preguntas_Adopcion 
        add constraint FK_fyqqbx6s9cbejhmyhq13pmcin 
        foreign key (id_asociacion) 
        references Asociaciones

    alter table Publicaciones 
        add constraint FK_g5mc0jk9hy19d6i3xwj2sls8r 
        foreign key (mascota_encontrada_id) 
        references Mascotas_Encontradas

    alter table Publicaciones 
        add constraint FK_ml4omwyd5oyc339n7rxjul50k 
        foreign key (id_asociacion) 
        references Asociaciones

    alter table Respuestas_Posibles 
        add constraint FK_srmj23llndqxwilo69y7nikqc 
        foreign key (pregunta_adopcion_id) 
        references Preguntas_Adopcion

    alter table Respuestas_Pregunta_Adopcion 
        add constraint FK_929mjpkj9tqrfdcq2uj2apjd0 
        foreign key (pregunta_adopcion_id) 
        references Preguntas_Adopcion

    alter table Respuestas_Pregunta_Adopcion 
        add constraint FK_r0991ovlgtf88wpl3i7r1yne1 
        foreign key (intencion_adoptar_id) 
        references IntencionesAdoptar

    alter table Respuestas_Pregunta_Adopcion 
        add constraint FK_k7xhjvwbirp0di8datvkqtsts 
        foreign key (mascota_adopcion_id) 
        references Mascotas_en_adopcion

    alter table Valores_Caracteristicas 
        add constraint FK_7ckj6rsah94vc6qhvak667gh4 
        foreign key (caracteristica_id) 
        references Caracteristicas

    alter table fotos_mascotas 
        add constraint FK_3ogo8ka4832humqch5y1jadva 
        foreign key (mascota_id) 
        references Mascotas

    alter table fotos_mascotas_encontradas 
        add constraint FK_76bxdqrbou65s1xn9a6jdx6fe 
        foreign key (mascota_encontrada_id) 
        references Mascotas_Encontradas
